server {
    listen 80;

    server_tokens off;

    location /static/ {
        alias /app/static/;
    }

    location /admin {
        include uwsgi_params;
        uwsgi_pass theatre-app:8000;
    }

    location / {
        include uwsgi_params;
        uwsgi_pass theatre-app:8000;
    }
}